version: '3.1'

volumes:
  pg_project:

services:
  db:
    image: postgres:latest
    restart: always
    container_name: tg_bot_template_db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_project:/var/lib/postgresql/tg_bot_template
    ports:
      - "5432:5432"

  onboarding_bot:
    container_name: tg_bot_template
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - db